/**
 * SlideDoc → .pptx Buffer renderer.
 *
 * Walks the renderer-agnostic SlideDoc tree and emits a PowerPoint
 * file using `pptxgenjs`. Builders never touch this module — they
 * return SlideDoc and we handle the layout-specific details here.
 *
 * Style choices that matter:
 *   - 16:9 widescreen (the default in modern decks).
 *   - Navy primary + gold accent — same TFB palette as the DOCX
 *     renderer so customers don't see two different brands across
 *     the bundle.
 *   - Title slide bleeds the navy background; content slides have
 *     a subtle navy header bar with white body so the deck reads
 *     as polished but not over-designed.
 *   - Speaker notes carry through to the PPTX presenter view —
 *     this is where Jason's coaching content lives, separate from
 *     what's projected.
 *
 * Why server-only: pptxgenjs has been audited as Node-friendly but
 * the Buffer assembly hits Node-specific code paths.
 */

import "server-only";
import PptxGenJS from "pptxgenjs";
import type { Slide, SlideBody, SlideDoc } from "./types";

// Brand palette — kept in hex strings (without `#`) per pptxgenjs
// API expectations.
const NAVY = "1E3A5F";
const NAVY_DARK = "162B47";
const GOLD = "C29D52";
const CREAM = "F8F5EE";
const WHITE = "FFFFFF";
const GREY_TEXT = "555555";
const GREY_LIGHT = "EEEEEE";

// 16:9 widescreen in inches.
const SLIDE_WIDTH = 13.333;
const SLIDE_HEIGHT = 7.5;

export async function renderPptx(deck: SlideDoc): Promise<Buffer> {
  const pres = new PptxGenJS();
  pres.layout = "LAYOUT_WIDE";
  pres.title = deck.title;
  pres.subject = deck.subtitle ?? "Generated by The Franchisor Blueprint";
  pres.company = "The Franchisor Blueprint";

  // ---- Title slide ----
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: NAVY };
  titleSlide.addText(deck.title, {
    x: 0.6,
    y: 2.4,
    w: SLIDE_WIDTH - 1.2,
    h: 1.4,
    fontSize: 44,
    bold: true,
    color: WHITE,
    fontFace: "Calibri",
    align: "center",
  });
  if (deck.subtitle) {
    titleSlide.addText(deck.subtitle, {
      x: 0.6,
      y: 3.9,
      w: SLIDE_WIDTH - 1.2,
      h: 0.8,
      fontSize: 22,
      italic: true,
      color: GOLD,
      fontFace: "Calibri",
      align: "center",
    });
  }
  if (deck.coverFields && deck.coverFields.length > 0) {
    const lines = deck.coverFields.map(
      (cf) => `${cf.label}: ${cf.value}`,
    );
    titleSlide.addText(lines.join("\n"), {
      x: 1.2,
      y: 5.0,
      w: SLIDE_WIDTH - 2.4,
      h: 1.5,
      fontSize: 14,
      color: WHITE,
      fontFace: "Calibri",
      align: "center",
      lineSpacing: 24,
    });
  }
  if (deck.disclaimer) {
    titleSlide.addText(deck.disclaimer, {
      x: 0.6,
      y: SLIDE_HEIGHT - 0.6,
      w: SLIDE_WIDTH - 1.2,
      h: 0.4,
      fontSize: 9,
      italic: true,
      color: CREAM,
      fontFace: "Calibri",
      align: "center",
    });
  }

  // ---- Body slides ----
  for (const slide of deck.slides) {
    addSlide(pres, slide);
  }

  // pptxgenjs's write() returns a Promise<string | Uint8Array | Blob | Buffer>;
  // when called server-side with the "nodebuffer" output, it gives us a Buffer.
  const out = await pres.write({ outputType: "nodebuffer" });
  return out as Buffer;
}

function addSlide(pres: PptxGenJS, slide: Slide): void {
  const s = pres.addSlide();

  // All non-title body slides share the same chrome: navy header bar
  // with the slide title in white, cream body area underneath.
  if (slide.layout === "title") {
    s.background = { color: NAVY };
    s.addText(slide.title, {
      x: 0.6,
      y: 2.6,
      w: SLIDE_WIDTH - 1.2,
      h: 1.4,
      fontSize: 40,
      bold: true,
      color: WHITE,
      align: "center",
      fontFace: "Calibri",
    });
    if (slide.subtitle) {
      s.addText(slide.subtitle, {
        x: 0.6,
        y: 4.1,
        w: SLIDE_WIDTH - 1.2,
        h: 0.8,
        fontSize: 22,
        italic: true,
        color: GOLD,
        align: "center",
        fontFace: "Calibri",
      });
    }
    if (slide.footer) {
      s.addText(slide.footer, {
        x: 0.6,
        y: SLIDE_HEIGHT - 0.6,
        w: SLIDE_WIDTH - 1.2,
        h: 0.4,
        fontSize: 11,
        color: CREAM,
        align: "center",
        fontFace: "Calibri",
      });
    }
    return;
  }

  if (slide.layout === "section") {
    // Section divider — full-bleed navy with large white heading.
    s.background = { color: NAVY_DARK };
    s.addText(slide.title, {
      x: 0.6,
      y: 3.0,
      w: SLIDE_WIDTH - 1.2,
      h: 1.6,
      fontSize: 44,
      bold: true,
      color: WHITE,
      align: "center",
      fontFace: "Calibri",
    });
    if (slide.caption) {
      s.addText(slide.caption, {
        x: 0.6,
        y: 4.6,
        w: SLIDE_WIDTH - 1.2,
        h: 0.8,
        fontSize: 18,
        italic: true,
        color: GOLD,
        align: "center",
        fontFace: "Calibri",
      });
    }
    return;
  }

  if (slide.layout === "stat") {
    s.background = { color: CREAM };
    s.addShape("rect", {
      x: 0,
      y: 0,
      w: SLIDE_WIDTH,
      h: 1.0,
      fill: { color: NAVY },
      line: { type: "none" },
    });
    if (slide.title) {
      s.addText(slide.title, {
        x: 0.6,
        y: 0.18,
        w: SLIDE_WIDTH - 1.2,
        h: 0.65,
        fontSize: 22,
        bold: true,
        color: WHITE,
        align: "left",
        fontFace: "Calibri",
      });
    }
    s.addText(slide.stat, {
      x: 0.6,
      y: 2.0,
      w: SLIDE_WIDTH - 1.2,
      h: 2.4,
      fontSize: 96,
      bold: true,
      color: NAVY,
      align: "center",
      fontFace: "Calibri",
    });
    s.addText(slide.caption, {
      x: 0.6,
      y: 4.6,
      w: SLIDE_WIDTH - 1.2,
      h: 1.2,
      fontSize: 22,
      color: GREY_TEXT,
      align: "center",
      fontFace: "Calibri",
      italic: true,
    });
    if (slide.notes) s.addNotes(slide.notes);
    return;
  }

  // Content + two-column slides share the navy header bar.
  s.background = { color: CREAM };
  s.addShape("rect", {
    x: 0,
    y: 0,
    w: SLIDE_WIDTH,
    h: 1.0,
    fill: { color: NAVY },
    line: { type: "none" },
  });
  s.addText(slide.title, {
    x: 0.6,
    y: 0.18,
    w: SLIDE_WIDTH - 1.2,
    h: 0.65,
    fontSize: 24,
    bold: true,
    color: WHITE,
    align: "left",
    fontFace: "Calibri",
  });
  s.addShape("rect", {
    x: 0,
    y: 0.95,
    w: SLIDE_WIDTH,
    h: 0.05,
    fill: { color: GOLD },
    line: { type: "none" },
  });

  if (slide.layout === "content") {
    addBodyBlocks(s, slide.body, {
      x: 0.6,
      y: 1.4,
      w: SLIDE_WIDTH - 1.2,
      h: SLIDE_HEIGHT - 1.6,
    });
    if (slide.notes) s.addNotes(slide.notes);
    return;
  }

  if (slide.layout === "two-column") {
    const colWidth = (SLIDE_WIDTH - 1.6) / 2; // 0.6 left margin + 0.4 gutter + 0.6 right margin
    if (slide.leftLabel) {
      s.addText(slide.leftLabel, {
        x: 0.6,
        y: 1.25,
        w: colWidth,
        h: 0.4,
        fontSize: 11,
        bold: true,
        color: GOLD,
        align: "left",
        fontFace: "Calibri",
        charSpacing: 2,
      });
    }
    addBodyBlocks(s, slide.left, {
      x: 0.6,
      y: 1.7,
      w: colWidth,
      h: SLIDE_HEIGHT - 1.9,
    });
    if (slide.rightLabel) {
      s.addText(slide.rightLabel, {
        x: 0.6 + colWidth + 0.4,
        y: 1.25,
        w: colWidth,
        h: 0.4,
        fontSize: 11,
        bold: true,
        color: GOLD,
        align: "left",
        fontFace: "Calibri",
        charSpacing: 2,
      });
    }
    addBodyBlocks(s, slide.right, {
      x: 0.6 + colWidth + 0.4,
      y: 1.7,
      w: colWidth,
      h: SLIDE_HEIGHT - 1.9,
    });
    if (slide.notes) s.addNotes(slide.notes);
    return;
  }
}

/** Render a body-block sequence inside a bounding region. The function
 *  flows blocks vertically; each block consumes `h * blockHeights`
 *  share. Tight enough for our single-region needs without a real
 *  layout engine. */
function addBodyBlocks(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  s: any,
  body: SlideBody[],
  region: { x: number; y: number; w: number; h: number },
): void {
  let y = region.y;
  const remaining = (): number => region.y + region.h - y;
  for (const block of body) {
    if (remaining() < 0.5) break;
    if (block.kind === "paragraph") {
      const h = Math.min(remaining(), 1.2);
      s.addText(block.text, {
        x: region.x,
        y,
        w: region.w,
        h,
        fontSize: 16,
        color: NAVY,
        bold: block.bold,
        fontFace: "Calibri",
        align: "left",
        valign: "top",
      });
      y += h + 0.15;
      continue;
    }
    if (block.kind === "bullets") {
      const h = Math.min(
        remaining(),
        Math.max(0.8, block.items.length * 0.45),
      );
      s.addText(
        block.items.map((t) => ({ text: t, options: { bullet: true } })),
        {
          x: region.x,
          y,
          w: region.w,
          h,
          fontSize: 16,
          color: NAVY,
          fontFace: "Calibri",
          paraSpaceAfter: 6,
          valign: "top",
        },
      );
      y += h + 0.2;
      continue;
    }
    if (block.kind === "kvlist") {
      const h = Math.min(remaining(), Math.max(0.8, block.rows.length * 0.45));
      const lines = block.rows.map((r) => `${r.label}: ${r.value}`);
      s.addText(lines.join("\n"), {
        x: region.x,
        y,
        w: region.w,
        h,
        fontSize: 14,
        color: NAVY,
        fontFace: "Calibri",
        lineSpacing: 22,
        valign: "top",
      });
      y += h + 0.2;
      continue;
    }
    if (block.kind === "stat") {
      const h = Math.min(remaining(), 2.4);
      s.addText(block.value, {
        x: region.x,
        y,
        w: region.w,
        h: 1.6,
        fontSize: 64,
        bold: true,
        color: NAVY,
        align: "center",
        fontFace: "Calibri",
      });
      s.addText(block.caption, {
        x: region.x,
        y: y + 1.6,
        w: region.w,
        h: 0.6,
        fontSize: 16,
        italic: true,
        color: GREY_TEXT,
        align: "center",
        fontFace: "Calibri",
      });
      y += h;
      continue;
    }
  }
  // Suppress the unused-warning on GREY_LIGHT — exported for future
  // table rendering once that lands.
  void GREY_LIGHT;
}
