/**
 * DeliverableDoc → .docx Buffer renderer.
 *
 * Walks the renderer-agnostic DeliverableDoc tree and emits a Microsoft
 * Word document using the `docx` npm package. The cover page is the
 * first section; each top-level DocSection becomes a page-broken
 * heading-1 region; bullets/tables follow the format-specific layout
 * for Word.
 *
 * Style choices that matter:
 *   - Garamond / Times for body — feels like a legal document, not a
 *     web app export.
 *   - Navy primary (#1E3A5F) for headings to echo the TFB brand.
 *   - Tables are full-width with subtle gray borders so they read as
 *     reference material, not data dumps.
 *   - Page numbers on every page after the cover.
 *   - Disclaimer rendered in italic at the bottom of the cover so the
 *     recipient knows up front this is a draft.
 */

import "server-only";
import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  HeadingLevel,
  LevelFormat,
  Packer,
  PageBreak,
  PageNumber,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import type { DeliverableDoc, DocBlock, DocSection } from "./types";

const NAVY = "1E3A5F";
const GOLD = "C29D52";
const GREY_BORDER = "D9D9D9";
const GREY_BG = "F4F4F2";

export async function renderDocx(doc: DeliverableDoc): Promise<Buffer> {
  const children: Paragraph[] = [];

  // ── Cover page ────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [new TextRun({ text: doc.title, bold: true, size: 44, color: NAVY })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 1200, after: 240 },
    }),
  );
  if (doc.subtitle) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: doc.subtitle, italics: true, size: 26, color: "555555" })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 600 },
      }),
    );
  }
  if (doc.coverFields && doc.coverFields.length > 0) {
    for (const cf of doc.coverFields) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${cf.label}: `, bold: true, size: 22, color: NAVY }),
            new TextRun({ text: cf.value, size: 22, color: "333333" }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 80 },
        }),
      );
    }
  }
  if (doc.disclaimer) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: " " })],
        spacing: { before: 800 },
      }),
    );
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: doc.disclaimer, italics: true, size: 18, color: "666666" }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { before: 200, line: 320 },
      }),
    );
  }
  children.push(
    new Paragraph({
      children: [new PageBreak()],
    }),
  );

  // ── Body ──────────────────────────────────────────────────────────────
  for (const section of doc.sections) {
    pushSection(children, section);
  }

  const docFile = new Document({
    creator: "The Franchisor Blueprint",
    title: doc.title,
    description: doc.subtitle ?? "Generated by The Franchisor Blueprint",
    styles: {
      default: {
        document: {
          run: { font: "Garamond", size: 22 },
          paragraph: { spacing: { line: 320 } },
        },
      },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: "Garamond", size: 32, bold: true, color: NAVY },
          paragraph: { spacing: { before: 480, after: 200 } },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: "Garamond", size: 26, bold: true, color: NAVY },
          paragraph: { spacing: { before: 320, after: 160 } },
        },
      ],
    },
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "•",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 360, hanging: 240 } } },
            },
          ],
        },
        {
          reference: "numbered",
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: "%1.",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 360, hanging: 240 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: { page: { margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 } } },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "Page ", size: 16, color: "888888" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "888888" }),
                  new TextRun({ text: " · Generated by The Franchisor Blueprint", size: 16, color: "888888" }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(docFile) as Promise<Buffer>;
}

function pushSection(out: Paragraph[], section: DocSection): void {
  out.push(
    new Paragraph({
      heading: section.level === 1 ? HeadingLevel.HEADING_1 : HeadingLevel.HEADING_2,
      children: [new TextRun({ text: section.title })],
    }),
  );
  for (const block of section.blocks) {
    pushBlock(out, block);
  }
  if (section.subsections) {
    for (const sub of section.subsections) {
      pushSection(out, sub);
    }
  }
}

function pushBlock(out: Paragraph[], block: DocBlock): void {
  switch (block.kind) {
    case "paragraph": {
      out.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: block.bold,
              italics: block.italic,
            }),
          ],
          spacing: { after: 120 },
        }),
      );
      return;
    }
    case "bullets": {
      for (const item of block.items) {
        out.push(
          new Paragraph({
            children: [new TextRun({ text: item })],
            numbering: { reference: "bullets", level: 0 },
          }),
        );
      }
      return;
    }
    case "numbered": {
      for (const item of block.items) {
        out.push(
          new Paragraph({
            children: [new TextRun({ text: item })],
            numbering: { reference: "numbered", level: 0 },
          }),
        );
      }
      return;
    }
    case "kvtable": {
      // Tables can't be passed via the Paragraph[] children helper — but
      // docx accepts arbitrary nodes in section.children. We work around
      // this by pushing each row as a 2-column borderless paragraph with
      // tab-stop-style alignment. This keeps the overall children array
      // type as Paragraph[] (cleaner) while still rendering as a clean
      // labeled list for the reader.
      const rows = block.rows;
      // Use a real Table node — `docx` allows mixed Paragraph + Table in
      // section.children, so we cast the array type at the section level.
      const table = new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: rows.map(
          (r) =>
            new TableRow({
              children: [
                new TableCell({
                  width: { size: 38, type: WidthType.PERCENTAGE },
                  shading: { type: ShadingType.CLEAR, fill: GREY_BG, color: "auto" },
                  margins: { top: 80, bottom: 80, left: 120, right: 120 },
                  borders: borderAll(GREY_BORDER),
                  children: [
                    new Paragraph({
                      children: [new TextRun({ text: r.label, bold: true, color: NAVY })],
                    }),
                  ],
                }),
                new TableCell({
                  width: { size: 62, type: WidthType.PERCENTAGE },
                  margins: { top: 80, bottom: 80, left: 120, right: 120 },
                  borders: borderAll(GREY_BORDER),
                  children: [
                    new Paragraph({ children: [new TextRun({ text: r.value })] }),
                  ],
                }),
              ],
            }),
        ),
      });
      // The docx library accepts Tables in section.children — we cast
      // here so the surrounding Paragraph[] typing stays simple.
      (out as unknown as Array<Paragraph | Table>).push(table);
      out.push(new Paragraph({ children: [new TextRun({ text: "" })] }));
      return;
    }
    case "table": {
      // N-column table with a header row. Headers are bold + grey-bg;
      // body rows alternate clean to keep the eye scanning.
      const headerRow = new TableRow({
        tableHeader: true,
        children: block.headers.map(
          (h) =>
            new TableCell({
              shading: { type: ShadingType.CLEAR, fill: GREY_BG, color: "auto" },
              margins: { top: 80, bottom: 80, left: 120, right: 120 },
              borders: borderAll(GREY_BORDER),
              children: [
                new Paragraph({
                  children: [new TextRun({ text: h, bold: true, color: NAVY })],
                }),
              ],
            }),
        ),
      });
      const bodyRows = block.rows.map(
        (cells) =>
          new TableRow({
            children: cells.map(
              (cellText) =>
                new TableCell({
                  margins: { top: 80, bottom: 80, left: 120, right: 120 },
                  borders: borderAll(GREY_BORDER),
                  children: [
                    new Paragraph({ children: [new TextRun({ text: cellText })] }),
                  ],
                }),
            ),
          }),
      );
      const table = new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [headerRow, ...bodyRows],
      });
      (out as unknown as Array<Paragraph | Table>).push(table);
      out.push(new Paragraph({ children: [new TextRun({ text: "" })] }));
      return;
    }
    case "callout": {
      const color = block.tone === "warning" ? "B45309" : block.tone === "info" ? GOLD : "555555";
      out.push(
        new Paragraph({
          children: [new TextRun({ text: block.text, italics: true, color })],
          spacing: { before: 120, after: 200 },
          shading: { type: ShadingType.CLEAR, fill: GREY_BG, color: "auto" },
        }),
      );
      return;
    }
    case "spacer": {
      out.push(new Paragraph({ children: [new TextRun({ text: "" })], spacing: { after: 80 } }));
      return;
    }
    case "pagebreak": {
      out.push(new Paragraph({ children: [new PageBreak()] }));
      return;
    }
  }
}

function borderAll(color: string) {
  return {
    top: { style: BorderStyle.SINGLE, size: 4, color },
    bottom: { style: BorderStyle.SINGLE, size: 4, color },
    left: { style: BorderStyle.SINGLE, size: 4, color },
    right: { style: BorderStyle.SINGLE, size: 4, color },
  };
}
