/**
 * Urgent inbox alert email — sent to Eric immediately when the
 * inbox review agent classifies a thread as "urgent".
 */

import { Heading, Hr, Section, Text } from "@react-email/components";
import {
  EmailLayout,
  eyebrowStyle,
  headingStyle,
  paragraphStyle,
  callOutStyle,
} from "./_layout";

export type InboxUrgentAlertPayload = {
  threadSubject: string;
  threadFrom: string;
  category: string;
  reason: string;
  summary: string;
  threadCount: number;
  reviewedAt: string;
};

export function inboxUrgentAlertSubject(p: InboxUrgentAlertPayload): string {
  return `🚨 Urgent inbox: ${p.threadSubject}`;
}

export function InboxUrgentAlertEmail(p: InboxUrgentAlertPayload) {
  return (
    <EmailLayout>
      <Text style={eyebrowStyle}>INBOX ALERT</Text>
      <Heading as="h1" style={headingStyle}>
        Urgent Email Needs Attention
      </Heading>

      <Section style={callOutStyle}>
        <Text style={{ ...paragraphStyle, margin: "0 0 4px", fontWeight: 700 }}>
          {p.threadSubject}
        </Text>
        <Text style={{ ...paragraphStyle, margin: "0 0 4px", color: "#888B92", fontSize: "13px" }}>
          From: {p.threadFrom}
        </Text>
        <Text style={{ ...paragraphStyle, margin: "0 0 4px", color: "#888B92", fontSize: "13px" }}>
          Why urgent: {p.reason}
        </Text>
      </Section>

      <Hr style={{ border: "none", borderTop: "1px solid rgba(30, 58, 95, 0.08)", margin: "24px 0" }} />

      <Text style={{ ...paragraphStyle, fontWeight: 600 }}>Summary</Text>
      <Text style={paragraphStyle}>{p.summary}</Text>

      <Hr style={{ border: "none", borderTop: "1px solid rgba(30, 58, 95, 0.08)", margin: "24px 0" }} />

      <Text style={{ ...paragraphStyle, color: "#888B92", fontSize: "12px" }}>
        This alert was generated by the inbox review agent at {p.reviewedAt}.
        {p.threadCount > 1 ? ` ${p.threadCount} threads were reviewed in this batch.` : ""}
        {" "}Check Gmail for the full thread.
      </Text>
    </EmailLayout>
  );
}

export function inboxUrgentAlertText(p: InboxUrgentAlertPayload): string {
  return [
    "🚨 URGENT INBOX ALERT",
    "",
    `Subject: ${p.threadSubject}`,
    `From: ${p.threadFrom}`,
    `Why urgent: ${p.reason}`,
    "",
    "Summary:",
    p.summary,
    "",
    `Reviewed at ${p.reviewedAt}. Check Gmail for the full thread.`,
  ].join("\n");
}
